# Generated by Django 6.0.5 on 2026-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analystapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
